config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get '/foos' => "users#foos"

  mount Fastengine::Engine => "/fast"

  concern :albumable do
    resources :albums
  end
  concern :postable do
    resources :posts
  end

  resources :pages
  resources :users do
    member do
      get :home
    end
    member do
      get :foos
    end
    resources :albums
    resources :photos
  end
  resources :events
  resources :albums, concerns: :postable
  resources :posts
  resources :friendships

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => "users#home"
end

app/models/album.rb
class Album < ApplicationRecord
  # The posts posted from desktop are by default added to the
  # "Timeline Photos" album if not created under an album

  # The posts posted from mobile are by default added to the
  # "Mobile Uploads" album if not created under an album
  belongs_to :user
  has_many :posts, dependent: :delete_all
  has_many :photos, :through => :posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user

  validates :name, presence: true
  validates :start_date, presence: true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, :class_name => 'User'
end

app/models/page.rb
class Page < ApplicationRecord
  belongs_to :user

  validates :name, presence: true

  mount_uploader :image, ImageUploader
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :post

  mount_uploader :image, ImageUploader
end

app/models/post.rb
class Post < ApplicationRecord
  # The posts posted from desktop are by default added to the
  # "Timeline Photos" album if not created under an album

  # The posts posted from mobile are by default added to the
  # "Mobile Uploads" album if not created under an album
  belongs_to :album
  has_many :photos, dependent: :delete_all
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :albums
  has_many :posts, :through => :albums
  has_many :friendships
  has_many :friends, :through => :friendships
  has_many :events
  has_many :pages

  after_create :create_default_albums

  def create_default_albums
    self.albums.create(name: "Mobile Uploads")
    self.albums.create(name: "Timeline Posts")
  end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def index

  end

  def create

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  layout "application"
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, only: [:index]

  def index
    @events = current_user.events
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @pages = current_user.pages
  end

  def create
  end

  def show
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def index
    @photos = []
    current_user.albums.each do |album|
      @photos << album.photos
    end
    @photos = @photos.flatten
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def create
    current_user.posts.create(post_params)
    redirect_to root_url
  end

  def index
    @posts = Post.all
  end

  private
  def post_params
    params.require(:post).permit(:text_content, :image)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def home
    # if request.user_agent =~ /Mobile/
    #   @album = current_user.albums.where(name: "Mobile Uploads").first
    # else
    #   @album = current_user.albums.where(name: "Timeline Posts").first
    # end
    # @post = current_user.posts.new
    # user_friends = current_user.try(:friends) if current_user.try(:friends).present?
    # @existing_posts = []
    # if user_friends.present?
    #   user_friends.each do |friend|
    #     @existing_posts = @existing_posts + friend.try(:posts)
    #   end
    # end
    @posts = current_user.posts
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/albums/index.html.erb
<h1>In album index</h1>

app/views/events/index.html.erb
<h1>Events</h1>
<% @events.each do |event| %>
  <%= event.start_date %>
  <%= event.name %>
  <br/>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Facebuk</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div>
      <%- flash.each do |name, msg| -%>
        <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
      <%- end -%>
      <%if user_signed_in? %>
        <%= link_to "Sign out", destroy_user_session_path, {:style => "float:right", :method => :delete} %>
        <br/><br/><br/><br/>

        <div class="sidenav"  style="width:15%">
          <%= link_to "News Feed", root_path %>
          <%= link_to "Events", events_path %>
          <%= link_to "Pages", pages_path %>
          <%= link_to "Photos", user_photos_path(current_user.id) %>
        </div>
      <%end%>
      <div class="main"  style="width:85%;float:right;">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/pages/index.html.erb
<h1>Your Pages</h1>
<% @pages.each do |page| %>
  <%= image_tag(page.image_url, size: "250x250") %>
  <%= page.name %>
  <br/><br/>
<% end %>

app/views/pages/show.html.erb
<h1>Pages#show</h1>
<p>Find me in app/views/pages/show.html.erb</p>

app/views/photos/index.html.erb
<h1>Photos</h1>
<h4>Photos of you</h4>
<% @photos.in_groups_of(4) do |photo_group| %>
  <div class="row">
    <% photo_group.each do |photo| %>
      <% if photo.present? %>
        <div><%= image_tag photo.image_url, :size => '237x157'%></div>
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/posts/_form.html.erb
<%= form_for [@album, @post], :html => {:class => "form-horizontal"} do |f| %>
  <div class="form-group">
    <%= f.label :text_content, :class => "col-sm-4 control-label" %>
    <%= f.text_field :text_content%>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-4 col-sm-8">
      <%= f.file_field :image %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-4 col-sm-8">
      <%= f.submit "submit" %>
    </div>
  </div>
<%end%>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
  <tr>
    <%= image_tag post.image_url if post.image_url.present? %>
    <br/>
    <%= post.text_content %>
    <br/>
  </tr>
<%end%>

app/views/users/home.html.erb
<h1>News Feed</h1>
<% if @posts.present? %>
  <% @posts.each do |post| %>
    <%= post.text_content %>
    <br/>
    <% if post.photos.present? %>
      <% post.photos.each do |photo| %>
        <%= image_tag photo.image_url, :size => '237x157' %>
      <% end %>
    <% end %>
    <br/>
  <% end %>
<% end %>
<%#= render partial: "posts/form" %>